<?php

/**
 * Implements hook_init().
 */
function ga_universal_init() {
  $ua = variable_get('ga_universal_ua', '');
  $domain = variable_get('ga_universal_domain', '');

  if (!empty($ua) && !empty($domain)) {
    drupal_add_js('(function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,\'script\',\'//www.google-analytics.com/analytics.js\',\'ga\');

ga(\'create\', \'' . $ua . '\', \'' . $domain . '\');
ga(\'send\', \'pageview\');', array('type' => 'inline', 'scope' => 'footer'));
  }
}

/**
 * Implements hook_permission().
 */
function ga_universal_permission() {
  return array(
    'administer ga universal' =>  array(
      'title' => t('Administer GA Universal'),
      'description' => t('View the admin page for GA Universal.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function ga_universal_menu() {
  $items = array();

  $items['admin/config/services/ga-universal'] = array(
    'title' => 'Google Analytics Universal',
    'description' => 'Configure the Google Analytics module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ga_universal_config'),
    'access arguments' => array('administer ga universal'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ga_universal.admin.inc',
  );

  return $items;
}
